dev:
  profile: dev
  mysql_username: root
  mysql_password: ""
  mysql_address: 127.0.0.1:3306
  mysql_db: learning_dev
  client_key: ""
  client_secret: ""
  app_id: "tt02c1747c9dc91dcb01"
  app_secret: ""

production:
  profile: production
  mysql_username: produser
  mysql_password: ""
  mysql_address: prodhost:3306
  mysql_db: learning_prod
  client_key: ""
  client_secret: ""
  app_id: "tt02c1747c9dc91dcb01"
  app_secret: ""