dev:
  profile: dev
  mysql_user: root
  mysql_password: ""
  mysql_host: 127.0.0.1:3306
  mysql_db: learning
  api_key: "your-production-api-key"
  api_secret: "your-production-api-secret"
  app_id: "your-app-id"

production:
  profile: production
  mysql_user: produser
  mysql_password: ""
  mysql_host: prodhost:3306
  mysql_db: prod_learning
  api_key: "your-production-api-key"
  api_secret: "your-production-api-secret"
  app_id: "your-app-id"