name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/learning-api:latest

      - name: Install dycloud-cli
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
          \. "$HOME/.nvm/nvm.sh"
          nvm install 22
          node -v
          nvm current
          npm -v
          npm install -g @open-dy/cloud-cli --registry=https://registry.npmmirror.com/
          dycloud --version

          dycloud login -e ${{ secrets.DOUYIN_USERNAME }} -p ${{ secrets.DOUYIN_PASSWORD }}
          dycloud env:switch --app-id tt02c1747c9dc91dcb01 --env dev
          dycloud container:push --image-id ${{ secrets.DOCKERHUB_USERNAME }}/learning-api:latest  --service-name learning-api
        env:
          DOUYIN_USERNAME: ${{ secrets.DOUYIN_USERNAME }}
          DOUYIN_PASSWORD: ${{ secrets.DOUYIN_PASSWORD }}

          

