name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/learning-api
      DOCKER_TAG_LATEST: latest
      DOCKER_TAG_VERSIONED: 1.0.0-${{ github.run_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: .
          push: true
          load: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG_LATEST }}
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG_VERSIONED }}
      - name: List Docker images (debugging)
        run: docker images
      - name: Setup Node.js and install dycloud-cli
        id: setup_node
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
          \. "$HOME/.nvm/nvm.sh"
          nvm install 22
          npm install -g @open-dy/cloud-cli --registry=https://registry.npmmirror.com/
          echo "::add-path::$HOME/.nvm/versions/node/v22/bin"
          echo "::set-output name=dycloud_version::$(dycloud --version)"
        shell: bash
      - name: push to Douyin Cloud
        timeout-minutes: 15
        run: |
          echo "Pushing Docker image to Douyin Cloud"
          TAG="soar/learning-api:latest"
          echo "TAG: $TAG"
          docker images
          IMAGE_ID=$(docker images --filter=reference="$TAG" --format "{{.ID}}")
          echo "Image ID: $IMAGE_ID"
          dycloud login -e ${{ secrets.DOUYIN_USERNAME }} -p ${{ secrets.DOUYIN_PASSWORD }}
          dycloud env:switch --app-id tt02c1747c9dc91dcb01 --env dev
          dycloud container:push --tag="${{ env.DOCKER_TAG_VERSIONED }}" --image-id="$IMAGE_ID" --service-name="learning-api" --remark="0.0.1"
        shell: bash
        env:
          DOUYIN_USERNAME: ${{ secrets.DOUYIN_USERNAME }}
          DOUYIN_PASSWORD: ${{ secrets.DOUYIN_PASSWORD }}
